#spring.application.name=ecom-ddev
spring:
  application:
    name: ecom-ddev
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_ddev
    username: root
    password: 280412092312
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8080

security:
  jwt:
    expiration-minutes: 30
    secret-key: RdSR7Ax0B5/+0cPoCz7ljuoOsU3sGRu3BgX/pRlsYW94ju9IhBKxX/UlE5XNg7rF